# Generated by Django 5.2.6 on 2025-09-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg', models.IntegerField(verbose_name='Telegram ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
        ),
    ]
