# Generated by Django 5.2.6 on 2025-09-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DayAdviceSubscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='EventsSubscriber',
            field=models.BooleanField(default=False),
        ),
    ]
