# Generated by Django 5.2.6 on 2025-09-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('organizer', models.CharField(max_length=100, verbose_name='Организатор')),
                ('description', models.TextField(blank=True, verbose_name='Описание мероприятия')),
                ('event_date', models.DateField(verbose_name='Дата проведения')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Максимальное количество участников')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
